# Generated by Django 5.1.1 on 2024-09-11 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=250, verbose_name='tarea')),
                ('status', models.CharField(choices=[('T', 'TODO'), ('I', 'IN-PROGRESS'), ('D', 'DONE')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
