# Generated by Django 5.1.1 on 2024-10-21 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=250, verbose_name='tarea')),
                ('description', models.CharField(max_length=250, verbose_name='descripcion')),
                ('name', models.CharField(max_length=125, verbose_name='nombre')),
            ],
        ),
    ]
